/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/corners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Suggest Corners
         * @description Detecta la hoja en la foto para precargar el ajuste manual de esquinas.
         */
        post: operations["suggest_corners_api_corners_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_projects__project_id__get"];
        put?: never;
        post?: never;
        /** Delete Project */
        delete: operations["delete_project_api_projects__project_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Image */
        get: operations["get_image_api_projects__project_id__image_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/model": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Model */
        put: operations["update_model_api_projects__project_id__model_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Progress */
        get: operations["get_progress_api_projects__project_id__progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/reanalyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reanalyze */
        post: operations["reanalyze_api_projects__project_id__reanalyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/scale": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Calibrate Scale */
        post: operations["calibrate_scale_api_projects__project_id__scale_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_create_project_api_projects_post */
        Body_create_project_api_projects_post: {
            /**
             * Corners
             * @description JSON [[x,y] x4] normalizado
             */
            corners?: string | null;
            /**
             * File
             * @description Foto, imagen o PDF del plano
             */
            file: string;
            /**
             * Name
             * @default Plano sin nombre
             */
            name: string;
        };
        /** Body_suggest_corners_api_corners_post */
        Body_suggest_corners_api_corners_post: {
            /**
             * File
             * @description Foto del plano
             */
            file: string;
        };
        /** BuildingModelDTO */
        BuildingModelDTO: {
            /**
             * Levels
             * @default []
             */
            levels: components["schemas"]["LevelDTO"][];
            /** Project Id */
            project_id: string;
            scale: components["schemas"]["ScaleDTO"];
            source_image?: components["schemas"]["SourceImageDTO"] | null;
            /**
             * Total Area
             * @description solo salida, m²
             */
            total_area?: number | null;
        };
        /**
         * CalibrateScaleDTO
         * @description Dos puntos (en píxeles de la imagen rectificada) y la distancia real entre ellos.
         */
        CalibrateScaleDTO: {
            a: components["schemas"]["PointDTO"];
            b: components["schemas"]["PointDTO"];
            /** Meters */
            meters: number;
        };
        /** CornersDTO */
        CornersDTO: {
            /**
             * Corners
             * @description Esquinas de la hoja detectadas (TL, TR, BR, BL) normalizadas 0..1, o null
             */
            corners: [
                number,
                number
            ][] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LevelDTO */
        LevelDTO: {
            /**
             * Elevation
             * @default 0
             */
            elevation: number;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Rooms
             * @default []
             */
            rooms: components["schemas"]["RoomDTO"][];
            /**
             * Walls
             * @default []
             */
            walls: components["schemas"]["WallDTO"][];
        };
        /** OpeningDTO */
        OpeningDTO: {
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
            /** Height */
            height: number;
            /** Id */
            id: string;
            kind: components["schemas"]["OpeningKind"];
            /**
             * Offset
             * @description metros desde Wall.start
             */
            offset: number;
            /**
             * Sill
             * @default 0
             */
            sill: number;
            /** Width */
            width: number;
        };
        /**
         * OpeningKind
         * @enum {string}
         */
        OpeningKind: "door" | "window";
        /** PointDTO */
        PointDTO: {
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** ProgressEventDTO */
        ProgressEventDTO: {
            /** Elapsed Ms */
            elapsed_ms?: number | null;
            /** Index */
            index: number;
            /** Message */
            message?: string | null;
            /**
             * Metrics
             * @default {}
             */
            metrics: {
                [key: string]: number;
            };
            preview?: components["schemas"]["BuildingModelDTO"] | null;
            /** Project Id */
            project_id: string;
            /** Stage */
            stage: string;
            /**
             * Status
             * @enum {string}
             */
            status: "started" | "completed" | "failed";
            /** Total */
            total: number;
        };
        /** ProjectCreatedDTO */
        ProjectCreatedDTO: {
            /** Id */
            id: string;
            status: components["schemas"]["ProjectStatus"];
        };
        /** ProjectDTO */
        ProjectDTO: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error?: string | null;
            /** Id */
            id: string;
            model?: components["schemas"]["BuildingModelDTO"] | null;
            /** Name */
            name: string;
            /**
             * Room Count
             * @default 0
             */
            room_count: number;
            status: components["schemas"]["ProjectStatus"];
            /** Total Area */
            total_area?: number | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ProjectStatus
         * @enum {string}
         */
        ProjectStatus: "pending" | "processing" | "ready" | "failed";
        /** ProjectSummaryDTO */
        ProjectSummaryDTO: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error?: string | null;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Room Count
             * @default 0
             */
            room_count: number;
            status: components["schemas"]["ProjectStatus"];
            /** Total Area */
            total_area?: number | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ReanalyzeDTO */
        ReanalyzeDTO: {
            /**
             * Corners
             * @description 4 esquinas [x,y] normalizadas 0..1 (TL, TR, BR, BL)
             */
            corners?: [
                number,
                number
            ][] | null;
        };
        /** RoomDTO */
        RoomDTO: {
            /**
             * Area
             * @description solo salida, m²
             */
            area?: number | null;
            /** @description solo salida */
            centroid?: components["schemas"]["PointDTO"] | null;
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Polygon */
            polygon: components["schemas"]["PointDTO"][];
        };
        /** ScaleDTO */
        ScaleDTO: {
            /**
             * Confidence
             * @default 0.5
             */
            confidence: number;
            /** Meters Per Pixel */
            meters_per_pixel: number;
            /**
             * Source
             * @default estimated
             * @enum {string}
             */
            source: "default" | "estimated" | "calibrated";
        };
        /** SourceImageDTO */
        SourceImageDTO: {
            /** Height Px */
            height_px: number;
            /** Key */
            key: string;
            /** Width Px */
            width_px: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WallDTO */
        WallDTO: {
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
            end: components["schemas"]["PointDTO"];
            /**
             * Height
             * @default 2.6
             */
            height: number;
            /** Id */
            id: string;
            /**
             * Length
             * @description solo salida
             */
            length?: number | null;
            /**
             * Material
             * @default plaster
             */
            material: string;
            /**
             * Openings
             * @default []
             */
            openings: components["schemas"]["OpeningDTO"][];
            start: components["schemas"]["PointDTO"];
            /**
             * Thickness
             * @default 0.15
             */
            thickness: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    suggest_corners_api_corners_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_suggest_corners_api_corners_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CornersDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_projects_api_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSummaryDTO"][];
                };
            };
        };
    };
    create_project_api_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_project_api_projects_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectCreatedDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_api_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_image_api_projects__project_id__image_get: {
        parameters: {
            query?: {
                kind?: string;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": unknown;
                    "image/png": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_model_api_projects__project_id__model_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuildingModelDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_progress_api_projects__project_id__progress_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressEventDTO"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reanalyze_api_projects__project_id__reanalyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ReanalyzeDTO"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectCreatedDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calibrate_scale_api_projects__project_id__scale_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CalibrateScaleDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
